### ISSUE TITLE
flutter qq分享成功点击返回应用,应用闪退是什么错误

### ISSUE THREAD

**Issue by BoyYangyang** [marekchen/flutter_qq#19]
E/AndroidRuntime(15655): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10103, result=-1, data=Intent { flg=0x24000000 cmp=com.digg.free_meal/com.tencent.connect.common.AssistActivity (has extras) }} to activity {com.di.fre/com.di.fre.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference

**Comment by 0131LWG** [comment]
一样的问题，请问有解决了吗

**Comment by Witcher-jufei** [comment]
+1，设备华为p30

**Comment by BoyYangyang** [comment]
我这边是和图片选择库中的代码冲突了

**Comment by wang-zeqi** [comment]
> 我这边是和图片选择库中的代码冲突了

请问你是怎么解决这种冲突的？

**Comment by zhangji92** [comment]
没解决
