### ISSUE TITLE
请问开始修改Android.xml文件应该怎么修改呢

### ISSUE THREAD

**Issue by yuyingjian123** [marekchen/flutter_qq#2]
把自己的activity文件全部换成你的吗，然后修改appid的值？
然后试着去调用的时候 出错了
onPressed: _handleLogin,

Future<Null> _handleLogin() async {
    try {
      var qqResult = await FlutterQq.login();
      var output;
      if (qqResult.code == 0) {
        output = "登录成功" + qqResult.response.toString();
      } else if (qqResult.code == 1) {
        output = "登录失败" + qqResult.message;
      } else {
        output = "用户取消";
      }
      setState(() {
       // _output = output;
      });
    } catch (error) {
      print("flutter_plugin_qq_example:" + error.toString());
    }
  }
界面无反应，控制台显示：
E/MethodChannel#flutter_qq(22381): Failed to handle method call
E/MethodChannel#flutter_qq(22381): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ten
cent.tauth.Tencent.login(android.app.Activity, java.lang.String, com.tencent.tauth.IUiListener)' on a null objec
t reference
E/MethodChannel#flutter_qq(22381):      at com.github.marekchen.flutterqq.FlutterQqPlugin.login(FlutterQqPlugin.
java:93)
E/MethodChannel#flutter_qq(22381):      at com.github.marekchen.flutterqq.FlutterQqPlugin.onMethodCall(FlutterQq
Plugin.java:66)
E/MethodChannel#flutter_qq(22381):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMe
ssage(MethodChannel.java:200)
E/MethodChannel#flutter_qq(22381):      at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNative
View.java:163)
E/MethodChannel#flutter_qq(22381):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_qq(22381):      at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter_qq(22381):      at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter_qq(22381):      at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter_qq(22381):      at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_qq(22381):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeIn
it.java:493)
E/MethodChannel#flutter_qq(22381):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (22381): flutter_plugin_qq_example:PlatformException(error, Attempt to invoke virtual method 'int com.
tencent.tauth.Tencent.login(android.app.Activity, java.lang.String, com.tencent.tauth.IUiListener)' on a null ob
ject reference, null)

怎么回事呢，求教

**Comment by marekchen** [comment]
follow the steps
