### ISSUE TITLE
致歉

### ISSUE THREAD

**Issue by neverwoodsS** [marekchen/flutter_qq#3]
最近我做的一个项目被人抄袭了。反思过后发现我当初做的 flutter_qq_bridge 也参考过不少你的代码，虽然在掘金上有说，但是 github 上忘了加。现在回想起来，当初也应该 fork 你的项目去做 iOS 功能的。在这里真挚的向你表示歉意。我会尝试将 pub 官网上的插件下架，今后有机会希望能参与到你的项目中来。

**Comment by marekchen** [comment]
没事
