### ISSUE TITLE
Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

### ISSUE THREAD

**Issue by ChuanWSwist** [marekchen/flutter_qq#4]
作者好，今天同时集成flutter_webview_plugin: ^0.3.5与flutter_qq: ^0.0.4，导致报错Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.似乎是有库冲突。因为对Android不太熟悉，在这里提下问.具体报错如下:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/8074222/58011832-b3ad5b80-7b25-11e9-9ce1-96fd05a21268.png">

**Comment by StarAndRainbow** [comment]
![image](https://user-images.githubusercontent.com/28133038/58012010-130b6b80-7b26-11e9-90bd-8ea2e1433968.png)

老哥，找不到AppDelegate.m，现在是添加到AppDelegate.swift下面了吗

**Comment by marekchen** [comment]
看log应该和我的工程没有关系，我没有用到support包。可能和androidx有关。

**Comment by ChuanWSwist** [comment]
swift工程是在AppDelegate.swift下面。

**Comment by marekchen** [comment]
> ![image](https://user-images.githubusercontent.com/28133038/58012010-130b6b80-7b26-11e9-90bd-8ea2e1433968.png)
> 
> 老哥，找不到AppDelegate.m，现在是添加到AppDelegate.swift下面了吗

你新建工程用的swift就写在AppDelegate.swift下，不过我是用oc写的，你自己转成swift

**Comment by StarAndRainbow** [comment]
> > ![图片](https://user-images.githubusercontent.com/28133038/58012010-130b6b80-7b26-11e9-90bd-8ea2e1433968.png)
> > 老哥，找不到AppDelegate.m，现在是添加到AppDelegate.swift下面了吗
> 
> 你新建工程用的迅速就写在AppDelegate.swift下，不过我是用OC写的，你自己转成迅速

我之前做的Android开发，我摸索一下，多谢老哥，祝好

**Comment by StarAndRainbow** [comment]
![image](https://user-images.githubusercontent.com/28133038/58014332-2f5dd700-7b2b-11e9-8e5e-d128b57b6a23.png)
遇到一样的问题了

**Comment by StarAndRainbow** [comment]
我尝试使用这个方法，解决了我的问题，链接：https://stackoverflow.com/questions/50676100/program-type-already-present-android-support-v4-os-resultreceivermyresultrecei
![image](https://user-images.githubusercontent.com/28133038/58014555-b743e100-7b2b-11e9-8e7a-579e3ee85e15.png)

**Comment by ChuanWSwist** [comment]
我这边的解决方案是build.gradle -> compileSdkVersion 27 ,降级flutter_webview_plugin版本^0.2.0

**Comment by hlj2722** [comment]
遇到同样的问题 



改为 compileSdkVersion 27
也报错 
merged.dir\values\values.xml:96: error: resource android:attr/fontVariationSettings not found.

**Comment by Vongolatt** [comment]
@ChuanWSwist ChuanWSwist 升级Android studio到最新版本，可以不降级flutter_webview_plugin,不要问我为什么，我也不知道。。。。。。。。。。。。。

**Comment by marekchen** [comment]
v0.0.6 release
compileSdkVersion 升级为28
使用androidx

**Comment by 0131LWG** [comment]
> > > ![图片](https://user-images.githubusercontent.com/28133038/58012010-130b6b80-7b26-11e9-90bd-8ea2e1433968.png)
> > > 老哥，找不到AppDelegate.m，现在是添加到AppDelegate.swift下面了吗
> > 
> > 
> > 你新建工程用的迅速就写在AppDelegate.swift下，不过我是用OC写的，你自己转成迅速
> 
> 我之前做的Android开发，我摸索一下，多谢老哥，祝好



> ![图片](https://user-images.githubusercontent.com/28133038/58014332-2f5dd700-7b2b-11e9-8e5e-d128b57b6a23.png)
> 遇到一样的问题了

请问一下AppDelegate.swift要怎么写呢？没有做过
