### ISSUE TITLE
Android 编译失败

### ISSUE THREAD

**Issue by ylytddd** [marekchen/flutter_qq#5]
报错信息如下: 
`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.customview:customview' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
`

移除flutter_qq 包, 编译就正常了.  安卓配置以及加上, 不知道需要另外做什么配置?

**Comment by marekchen** [comment]
这周末 我看一下，最近flutter添加了androidx支持

**Comment by marekchen** [comment]
我已经换成androidx，可以再试一下

**Comment by dsmjoy** [comment]
tencent.login(registrar.activity(), scope, loginListener);
                   ^
  找不到androidx.fragment.app.Fragment的类文件

现在狐仙这个问题.   这是什么?

**Comment by ylytddd** [comment]
> 我已经换成androidx，可以再试一下

可以了
